"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from moovio_sdk.types import BaseModel
from moovio_sdk.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Dict, List
from typing_extensions import Annotated, TypedDict


class DisablePaymentLinkRequestTypedDict(TypedDict):
    account_id: str
    r"""The merchant account ID."""
    payment_link_code: str


class DisablePaymentLinkRequest(BaseModel):
    account_id: Annotated[
        str,
        pydantic.Field(alias="accountID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The merchant account ID."""

    payment_link_code: Annotated[
        str,
        pydantic.Field(alias="paymentLinkCode"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]


class DisablePaymentLinkResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]


class DisablePaymentLinkResponse(BaseModel):
    headers: Dict[str, List[str]]
