"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from moovio_sdk.models.components import dispute as components_dispute
from moovio_sdk.types import BaseModel
from moovio_sdk.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Dict, List
from typing_extensions import Annotated, TypedDict


class GetDisputeRequestTypedDict(TypedDict):
    account_id: str
    dispute_id: str


class GetDisputeRequest(BaseModel):
    account_id: Annotated[
        str,
        pydantic.Field(alias="accountID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    dispute_id: Annotated[
        str,
        pydantic.Field(alias="disputeID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]


class GetDisputeResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: components_dispute.DisputeTypedDict


class GetDisputeResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: components_dispute.Dispute
