"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from moovio_sdk.types import BaseModel
from moovio_sdk.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Dict, List, Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class GetDisputeEvidenceDataRequestTypedDict(TypedDict):
    account_id: str
    dispute_id: str
    evidence_id: str


class GetDisputeEvidenceDataRequest(BaseModel):
    account_id: Annotated[
        str,
        pydantic.Field(alias="accountID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    dispute_id: Annotated[
        str,
        pydantic.Field(alias="disputeID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    evidence_id: Annotated[
        str,
        pydantic.Field(alias="evidenceID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]


GetDisputeEvidenceDataResponseResultTypedDict = TypeAliasType(
    "GetDisputeEvidenceDataResponseResultTypedDict",
    Union[httpx.Response, httpx.Response, httpx.Response],
)


GetDisputeEvidenceDataResponseResult = TypeAliasType(
    "GetDisputeEvidenceDataResponseResult",
    Union[httpx.Response, httpx.Response, httpx.Response],
)


class GetDisputeEvidenceDataResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: GetDisputeEvidenceDataResponseResultTypedDict


class GetDisputeEvidenceDataResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: GetDisputeEvidenceDataResponseResult
