"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from moovio_sdk.models.components import fullissuedcard as components_fullissuedcard
from moovio_sdk.types import BaseModel
from moovio_sdk.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Dict, List
from typing_extensions import Annotated, TypedDict


class GetFullIssuedCardRequestTypedDict(TypedDict):
    account_id: str
    r"""The Moov business account for which the card was issued."""
    issued_card_id: str


class GetFullIssuedCardRequest(BaseModel):
    account_id: Annotated[
        str,
        pydantic.Field(alias="accountID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The Moov business account for which the card was issued."""

    issued_card_id: Annotated[
        str,
        pydantic.Field(alias="issuedCardID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]


class GetFullIssuedCardResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: components_fullissuedcard.FullIssuedCardTypedDict


class GetFullIssuedCardResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: components_fullissuedcard.FullIssuedCard
