"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from moovio_sdk.models.components import (
    underwriting as components_underwriting,
    updateunderwriting as components_updateunderwriting,
)
from moovio_sdk.types import BaseModel
from moovio_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing import Dict, List
from typing_extensions import Annotated, TypedDict


class UpsertUnderwritingRequestTypedDict(TypedDict):
    account_id: str
    update_underwriting: components_updateunderwriting.UpdateUnderwritingTypedDict


class UpsertUnderwritingRequest(BaseModel):
    account_id: Annotated[
        str,
        pydantic.Field(alias="accountID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    update_underwriting: Annotated[
        components_updateunderwriting.UpdateUnderwriting,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class UpsertUnderwritingResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: components_underwriting.UnderwritingTypedDict


class UpsertUnderwritingResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: components_underwriting.Underwriting
