"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .cardverificationresult import CardVerificationResult
from moovio_sdk.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AccountNameVerificationTypedDict(TypedDict):
    r"""The results of submitting cardholder name to a card network for verification."""

    first_name: NotRequired[CardVerificationResult]
    r"""Verification result of the cardholder's first name."""
    last_name: NotRequired[CardVerificationResult]
    r"""Verification result of the cardholder's last name."""
    middle_name: NotRequired[CardVerificationResult]
    r"""Verification result of the cardholder's middle name."""
    full_name: NotRequired[CardVerificationResult]
    r"""Verification result of the cardholder's full name."""


class AccountNameVerification(BaseModel):
    r"""The results of submitting cardholder name to a card network for verification."""

    first_name: Annotated[
        Optional[CardVerificationResult], pydantic.Field(alias="firstName")
    ] = None
    r"""Verification result of the cardholder's first name."""

    last_name: Annotated[
        Optional[CardVerificationResult], pydantic.Field(alias="lastName")
    ] = None
    r"""Verification result of the cardholder's last name."""

    middle_name: Annotated[
        Optional[CardVerificationResult], pydantic.Field(alias="middleName")
    ] = None
    r"""Verification result of the cardholder's middle name."""

    full_name: Annotated[
        Optional[CardVerificationResult], pydantic.Field(alias="fullName")
    ] = None
    r"""Verification result of the cardholder's full name."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["firstName", "lastName", "middleName", "fullName"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    AccountNameVerification.model_rebuild()
except NameError:
    pass
