"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .debitholdperiod import DebitHoldPeriod
from .seccode import SECCode
from .transferachaddendarecord import (
    TransferACHAddendaRecord,
    TransferACHAddendaRecordTypedDict,
)
from moovio_sdk.models import components
from moovio_sdk.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import field_serializer, model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ACHDebitOptionsTypedDict(TypedDict):
    company_entry_description: NotRequired[str]
    r"""An optional override of the default NACHA company entry description for a transfer."""
    originating_company_name: NotRequired[str]
    r"""An optional override of the default NACHA company name for a transfer."""
    sec_code: NotRequired[SECCode]
    r"""Code used to identify the ACH authorization method."""
    debit_hold_period: NotRequired[DebitHoldPeriod]
    r"""An optional override of your default ACH hold period in banking days. The hold period must be longer than or equal to your default setting."""
    addenda: NotRequired[List[TransferACHAddendaRecordTypedDict]]


class ACHDebitOptions(BaseModel):
    company_entry_description: Annotated[
        Optional[str], pydantic.Field(alias="companyEntryDescription")
    ] = None
    r"""An optional override of the default NACHA company entry description for a transfer."""

    originating_company_name: Annotated[
        Optional[str], pydantic.Field(alias="originatingCompanyName")
    ] = None
    r"""An optional override of the default NACHA company name for a transfer."""

    sec_code: Annotated[Optional[SECCode], pydantic.Field(alias="secCode")] = None
    r"""Code used to identify the ACH authorization method."""

    debit_hold_period: Annotated[
        Optional[DebitHoldPeriod], pydantic.Field(alias="debitHoldPeriod")
    ] = None
    r"""An optional override of your default ACH hold period in banking days. The hold period must be longer than or equal to your default setting."""

    addenda: Optional[List[TransferACHAddendaRecord]] = None

    @field_serializer("sec_code")
    def serialize_sec_code(self, value):
        if isinstance(value, str):
            try:
                return components.SECCode(value)
            except ValueError:
                return value
        return value

    @field_serializer("debit_hold_period")
    def serialize_debit_hold_period(self, value):
        if isinstance(value, str):
            try:
                return components.DebitHoldPeriod(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "companyEntryDescription",
                "originatingCompanyName",
                "secCode",
                "debitHoldPeriod",
                "addenda",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    ACHDebitOptions.model_rebuild()
except NameError:
    pass
