"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .createbusinessprofileupdate import (
    CreateBusinessProfileUpdate,
    CreateBusinessProfileUpdateTypedDict,
)
from .createindividualprofileupdate import (
    CreateIndividualProfileUpdate,
    CreateIndividualProfileUpdateTypedDict,
)
from moovio_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CreateProfileUpdateTypedDict(TypedDict):
    individual: NotRequired[CreateIndividualProfileUpdateTypedDict]
    business: NotRequired[CreateBusinessProfileUpdateTypedDict]


class CreateProfileUpdate(BaseModel):
    individual: Optional[CreateIndividualProfileUpdate] = None

    business: Optional[CreateBusinessProfileUpdate] = None
