"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .createtippresets import CreateTipPresets, CreateTipPresetsTypedDict
from moovio_sdk.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateTransferConfigTypedDict(TypedDict):
    tip_presets: NotRequired[CreateTipPresetsTypedDict]


class CreateTransferConfig(BaseModel):
    tip_presets: Annotated[
        Optional[CreateTipPresets], pydantic.Field(alias="tipPresets")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["tipPresets"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    CreateTransferConfig.model_rebuild()
except NameError:
    pass
