"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .amountdecimal import AmountDecimal, AmountDecimalTypedDict
from .reversalamountdetails import ReversalAmountDetails, ReversalAmountDetailsTypedDict
from moovio_sdk.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateReversalTypedDict(TypedDict):
    amount: AmountDecimalTypedDict
    r"""Amount to reverse.
    Before v2026.10, specify the amount in integer cents.
    For supported auth-capture `card-payment` reversals in v2026.10 and later, a transfer with no captures uses the full `capturableAmount`.
    For those transfers with one final capture, a cancellation uses the full capture amount, while a refund may be partial.
    """
    amount_details: NotRequired[ReversalAmountDetailsTypedDict]
    r"""Breakdown of the reversed amount."""


class CreateReversal(BaseModel):
    amount: AmountDecimal
    r"""Amount to reverse.
    Before v2026.10, specify the amount in integer cents.
    For supported auth-capture `card-payment` reversals in v2026.10 and later, a transfer with no captures uses the full `capturableAmount`.
    For those transfers with one final capture, a cancellation uses the full capture amount, while a refund may be partial.
    """

    amount_details: Annotated[
        Optional[ReversalAmountDetails], pydantic.Field(alias="amountDetails")
    ] = None
    r"""Breakdown of the reversed amount."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["amountDetails"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    CreateReversal.model_rebuild()
except NameError:
    pass
