"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .googlepayresponse import GooglePayResponse, GooglePayResponseTypedDict
from enum import Enum
from moovio_sdk.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class LinkedGooglePayPaymentMethodPaymentMethodType(str, Enum):
    GOOGLE_PAY = "google-pay"


class LinkedGooglePayPaymentMethodTypedDict(TypedDict):
    payment_method_id: str
    r"""The new payment method's ID."""
    payment_method_type: LinkedGooglePayPaymentMethodPaymentMethodType
    google_pay: GooglePayResponseTypedDict
    r"""Describes a Google Pay token on a Moov account."""


class LinkedGooglePayPaymentMethod(BaseModel):
    payment_method_id: Annotated[str, pydantic.Field(alias="paymentMethodID")]
    r"""The new payment method's ID."""

    payment_method_type: Annotated[
        LinkedGooglePayPaymentMethodPaymentMethodType,
        pydantic.Field(alias="paymentMethodType"),
    ]

    google_pay: Annotated[GooglePayResponse, pydantic.Field(alias="googlePay")]
    r"""Describes a Google Pay token on a Moov account."""


try:
    LinkedGooglePayPaymentMethod.model_rebuild()
except NameError:
    pass
