"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .address import Address, AddressTypedDict
from .cardexpiration import CardExpiration, CardExpirationTypedDict
from .issuingcontrols import IssuingControls, IssuingControlsTypedDict
from moovio_sdk.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class RequestCardTypedDict(TypedDict):
    authorized_user_account_id: NotRequired[str]
    nickname: NotRequired[str]
    metadata: NotRequired[Dict[str, str]]
    r"""Free-form key-value pair list. Useful for storing information that is not captured elsewhere."""
    billing_address: NotRequired[AddressTypedDict]
    expiration: NotRequired[CardExpirationTypedDict]
    r"""The expiration date of the card or token."""
    controls: NotRequired[IssuingControlsTypedDict]


class RequestCard(BaseModel):
    authorized_user_account_id: Annotated[
        Optional[str], pydantic.Field(alias="authorizedUserAccountID")
    ] = None

    nickname: Optional[str] = None

    metadata: Optional[Dict[str, str]] = None
    r"""Free-form key-value pair list. Useful for storing information that is not captured elsewhere."""

    billing_address: Annotated[
        Optional[Address], pydantic.Field(alias="billingAddress")
    ] = None

    expiration: Optional[CardExpiration] = None
    r"""The expiration date of the card or token."""

    controls: Optional[IssuingControls] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "authorizedUserAccountID",
                "nickname",
                "metadata",
                "billingAddress",
                "expiration",
                "controls",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    RequestCard.model_rebuild()
except NameError:
    pass
