"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .amountdecimal import AmountDecimal, AmountDecimalTypedDict
from .tipcalculationbasis import TipCalculationBasis
from moovio_sdk.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TipPresetsTypedDict(TypedDict):
    r"""Tip presets when calculating tips for a transfer."""

    calculation_basis: NotRequired[TipCalculationBasis]
    r"""Defines which amount should be used when calculating the final payment total. This calculation applies for percentage tip values.
    - `pre-tax`: Tip amounts are calculated using the subtotal amount before taxes
    - `post-tax`: Tip amounts are calculated using the subtotal amount + taxes
    """
    percentage_options: NotRequired[List[int]]
    r"""Defines the set of suggested tip preset values presented to customers. Percentages must be between 0 and 100 (exclusive) and must be unique. A maximum of 3 values are allowed."""
    fixed_amount_options: NotRequired[List[AmountDecimalTypedDict]]
    r"""Defines the set of suggested tip preset values presented to customers. Fixed amounts must be positive and unique. A maximum of 3 values are allowed."""


class TipPresets(BaseModel):
    r"""Tip presets when calculating tips for a transfer."""

    calculation_basis: Annotated[
        Optional[TipCalculationBasis], pydantic.Field(alias="calculationBasis")
    ] = None
    r"""Defines which amount should be used when calculating the final payment total. This calculation applies for percentage tip values.
    - `pre-tax`: Tip amounts are calculated using the subtotal amount before taxes
    - `post-tax`: Tip amounts are calculated using the subtotal amount + taxes
    """

    percentage_options: Annotated[
        Optional[List[int]], pydantic.Field(alias="percentageOptions")
    ] = None
    r"""Defines the set of suggested tip preset values presented to customers. Percentages must be between 0 and 100 (exclusive) and must be unique. A maximum of 3 values are allowed."""

    fixed_amount_options: Annotated[
        Optional[List[AmountDecimal]], pydantic.Field(alias="fixedAmountOptions")
    ] = None
    r"""Defines the set of suggested tip preset values presented to customers. Fixed amounts must be positive and unique. A maximum of 3 values are allowed."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["calculationBasis", "percentageOptions", "fixedAmountOptions"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TipPresets.model_rebuild()
except NameError:
    pass
