"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from moovio_sdk.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class TransferControlsTypedDict(TypedDict):
    r"""Controls for transfers created through a given partner"""

    account_id: str
    r"""ID of the merchant account."""
    partner_account_id: str
    r"""ID of the partner account."""
    debt_repayment: bool
    r"""Indicates if the account is configured for debt repayment."""
    allow_dynamic_descriptor: bool
    r"""Indicates if the account is allowed to set dynamic descriptors on transfers."""
    allow_surcharge: bool
    r"""Indicates if the account is allowed to apply surcharges to transfers."""


class TransferControls(BaseModel):
    r"""Controls for transfers created through a given partner"""

    account_id: Annotated[str, pydantic.Field(alias="accountID")]
    r"""ID of the merchant account."""

    partner_account_id: Annotated[str, pydantic.Field(alias="partnerAccountID")]
    r"""ID of the partner account."""

    debt_repayment: Annotated[bool, pydantic.Field(alias="debtRepayment")]
    r"""Indicates if the account is configured for debt repayment."""

    allow_dynamic_descriptor: Annotated[
        bool, pydantic.Field(alias="allowDynamicDescriptor")
    ]
    r"""Indicates if the account is allowed to set dynamic descriptors on transfers."""

    allow_surcharge: Annotated[bool, pydantic.Field(alias="allowSurcharge")]
    r"""Indicates if the account is allowed to apply surcharges to transfers."""


try:
    TransferControls.model_rebuild()
except NameError:
    pass
