"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from moovio_sdk import utils


class TransferType(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The rail and direction used to move funds for a transfer."""

    CARD_PAYMENT = "card-payment"
    PUSH_TO_CARD = "push-to-card"
    PULL_FROM_CARD = "pull-from-card"
    ACH_DEBIT = "ach-debit"
    ACH_CREDIT = "ach-credit"
    ACH_DEBIT_TO_ACH_CREDIT = "ach-debit-to-ach-credit"
    INSTANT_BANK_CREDIT = "instant-bank-credit"
    WALLET = "wallet"
    WIRE_CREDIT = "wire-credit"
