workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    latest:
        inputs:
            - location: registry.speakeasyapi.dev/moov/moov/api-latest

targets:
    latest:
        target: python
        source: latest
        publish:
            pypi:
                token: $pypi_token
