workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    latest:
        inputs:
            - location: registry.speakeasyapi.dev/moov/moov/api-v2025.10.00
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/moov/moov/python-v2025.10.00
targets:
    latest:
        target: python
        source: latest
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/moov/moov/v2025.10.00-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
