workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    dev:
        inputs:
            - location: registry.speakeasyapi.dev/moov/moov/api-dev
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/moov/moov/python-dev
targets:
    latest:
        target: python
        source: dev
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/moov/moov/dev-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
