"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "moovio_sdk"
__version__: str = "25.7.11"
__openapi_doc_version__: str = "v2025.07.00"
__gen_version__: str = "2.835.2"
__user_agent__: str = "speakeasy-sdk/python 25.7.11 2.835.2 v2025.07.00 moovio_sdk"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
