"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .accountcapability import AccountCapability, AccountCapabilityTypedDict
from .accounttype import AccountType
from .mode import Mode
from .profile import Profile, ProfileTypedDict
from .verification import Verification, VerificationTypedDict
from datetime import datetime
from moov.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TermsOfServiceTypedDict(TypedDict):
    r"""Describes the acceptance of the Terms of Service."""

    accepted_date: datetime
    accepted_ip: str


class TermsOfService(BaseModel):
    r"""Describes the acceptance of the Terms of Service."""

    accepted_date: Annotated[datetime, pydantic.Field(alias="acceptedDate")]

    accepted_ip: Annotated[str, pydantic.Field(alias="acceptedIP")]


class AccountPhoneTypedDict(TypedDict):
    number: NotRequired[str]
    country_code: NotRequired[str]


class AccountPhone(BaseModel):
    number: Optional[str] = None

    country_code: Annotated[Optional[str], pydantic.Field(alias="countryCode")] = None


class AccountAddressTypedDict(TypedDict):
    address_line1: str
    city: str
    state_or_province: str
    postal_code: str
    country: str
    address_line2: NotRequired[str]


class AccountAddress(BaseModel):
    address_line1: Annotated[str, pydantic.Field(alias="addressLine1")]

    city: str

    state_or_province: Annotated[str, pydantic.Field(alias="stateOrProvince")]

    postal_code: Annotated[str, pydantic.Field(alias="postalCode")]

    country: str

    address_line2: Annotated[Optional[str], pydantic.Field(alias="addressLine2")] = None


class CustomerSupportTypedDict(TypedDict):
    r"""User-provided information that can be displayed on credit card transactions for customers to use when contacting a customer support team. This data is only allowed on a business account."""

    phone: NotRequired[Nullable[AccountPhoneTypedDict]]
    email: NotRequired[str]
    r"""Email address."""
    address: NotRequired[Nullable[AccountAddressTypedDict]]
    website: NotRequired[str]


class CustomerSupport(BaseModel):
    r"""User-provided information that can be displayed on credit card transactions for customers to use when contacting a customer support team. This data is only allowed on a business account."""

    phone: OptionalNullable[AccountPhone] = UNSET

    email: Optional[str] = None
    r"""Email address."""

    address: OptionalNullable[AccountAddress] = UNSET

    website: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["phone", "email", "address", "website"]
        nullable_fields = ["phone", "address"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


class CardPaymentTypedDict(TypedDict):
    r"""User provided settings to manage card payments. This data is only allowed on a business account."""

    statement_descriptor: NotRequired[str]
    r"""The description that shows up on credit card transactions. This will default to the accounts display name on account creation."""


class CardPayment(BaseModel):
    r"""User provided settings to manage card payments. This data is only allowed on a business account."""

    statement_descriptor: Annotated[
        Optional[str], pydantic.Field(alias="statementDescriptor")
    ] = None
    r"""The description that shows up on credit card transactions. This will default to the accounts display name on account creation."""


class AchPaymentTypedDict(TypedDict):
    r"""User provided settings to manage ACH payments."""

    company_name: NotRequired[str]
    r"""The description that shows up on ACH transactions. This will default to the account's display name on account creation."""


class AchPayment(BaseModel):
    r"""User provided settings to manage ACH payments."""

    company_name: Annotated[Optional[str], pydantic.Field(alias="companyName")] = None
    r"""The description that shows up on ACH transactions. This will default to the account's display name on account creation."""


class SettingsTypedDict(TypedDict):
    r"""User provided settings to manage an account."""

    card_payment: NotRequired[Nullable[CardPaymentTypedDict]]
    ach_payment: NotRequired[Nullable[AchPaymentTypedDict]]


class Settings(BaseModel):
    r"""User provided settings to manage an account."""

    card_payment: Annotated[
        OptionalNullable[CardPayment], pydantic.Field(alias="cardPayment")
    ] = UNSET

    ach_payment: Annotated[
        OptionalNullable[AchPayment], pydantic.Field(alias="achPayment")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["cardPayment", "achPayment"]
        nullable_fields = ["cardPayment", "achPayment"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


class AccountTypedDict(TypedDict):
    r"""Describes a Moov account."""

    mode: NotRequired[Mode]
    r"""The mode this account is allowed to be used within."""
    account_id: NotRequired[str]
    r"""UUID v4"""
    account_type: NotRequired[AccountType]
    r"""The type of entity represented by this account."""
    display_name: NotRequired[str]
    profile: NotRequired[ProfileTypedDict]
    r"""Describes a Moov account profile."""
    metadata: NotRequired[Dict[str, str]]
    r"""Free-form key-value pair list. Useful for storing information that is not captured elsewhere."""
    terms_of_service: NotRequired[Nullable[TermsOfServiceTypedDict]]
    capabilities: NotRequired[List[AccountCapabilityTypedDict]]
    verification: NotRequired[VerificationTypedDict]
    r"""Describes identity verification status and relevant identity verification documents."""
    foreign_id: NotRequired[str]
    r"""Optional alias from a foreign/external system which can be used to reference this resource."""
    customer_support: NotRequired[Nullable[CustomerSupportTypedDict]]
    settings: NotRequired[Nullable[SettingsTypedDict]]
    created_on: NotRequired[datetime]
    updated_on: NotRequired[datetime]
    disconnected_on: NotRequired[Nullable[datetime]]


class Account(BaseModel):
    r"""Describes a Moov account."""

    mode: Optional[Mode] = None
    r"""The mode this account is allowed to be used within."""

    account_id: Annotated[Optional[str], pydantic.Field(alias="accountID")] = None
    r"""UUID v4"""

    account_type: Annotated[
        Optional[AccountType], pydantic.Field(alias="accountType")
    ] = None
    r"""The type of entity represented by this account."""

    display_name: Annotated[Optional[str], pydantic.Field(alias="displayName")] = None

    profile: Optional[Profile] = None
    r"""Describes a Moov account profile."""

    metadata: Optional[Dict[str, str]] = None
    r"""Free-form key-value pair list. Useful for storing information that is not captured elsewhere."""

    terms_of_service: Annotated[
        OptionalNullable[TermsOfService], pydantic.Field(alias="termsOfService")
    ] = UNSET

    capabilities: Optional[List[AccountCapability]] = None

    verification: Optional[Verification] = None
    r"""Describes identity verification status and relevant identity verification documents."""

    foreign_id: Annotated[Optional[str], pydantic.Field(alias="foreignID")] = None
    r"""Optional alias from a foreign/external system which can be used to reference this resource."""

    customer_support: Annotated[
        OptionalNullable[CustomerSupport], pydantic.Field(alias="customerSupport")
    ] = UNSET

    settings: OptionalNullable[Settings] = UNSET

    created_on: Annotated[Optional[datetime], pydantic.Field(alias="createdOn")] = None

    updated_on: Annotated[Optional[datetime], pydantic.Field(alias="updatedOn")] = None

    disconnected_on: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="disconnectedOn")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "mode",
            "accountID",
            "accountType",
            "displayName",
            "profile",
            "metadata",
            "termsOfService",
            "capabilities",
            "verification",
            "foreignID",
            "customerSupport",
            "settings",
            "createdOn",
            "updatedOn",
            "disconnectedOn",
        ]
        nullable_fields = [
            "termsOfService",
            "customerSupport",
            "settings",
            "disconnectedOn",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
