"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from moov.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class AccountUpdatedTypedDict(TypedDict):
    account_id: str
    r"""ID of the account"""


class AccountUpdated(BaseModel):
    account_id: Annotated[str, pydantic.Field(alias="accountID")]
    r"""ID of the account"""
