"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from moov.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class BalanceUpdatedTypedDict(TypedDict):
    wallet_id: str
    r"""ID of the Wallet"""
    account_id: NotRequired[str]
    r"""ID of the Account associated with the wallet"""


class BalanceUpdated(BaseModel):
    wallet_id: Annotated[str, pydantic.Field(alias="walletID")]
    r"""ID of the Wallet"""

    account_id: Annotated[Optional[str], pydantic.Field(alias="accountID")] = None
    r"""ID of the Account associated with the wallet"""
