"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .bankaccountstatus import BankAccountStatus
from .bankaccountstatusreason import BankAccountStatusReason
from .bankaccounttype import BankAccountType
from .basicpaymentmethod import BasicPaymentMethod, BasicPaymentMethodTypedDict
from .exceptiondetails import ExceptionDetails, ExceptionDetailsTypedDict
from .holdertype import HolderType
from datetime import datetime
from moov.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class BankAccountResponseTypedDict(TypedDict):
    r"""Describes a bank account on a Moov account."""

    bank_account_id: NotRequired[str]
    r"""UUID v4"""
    fingerprint: NotRequired[str]
    r"""Once the bank account is linked, we don't reveal the full bank account number. The fingerprint acts as a way to identify whether two linked bank accounts are the same."""
    status: NotRequired[BankAccountStatus]
    r"""The bank account status."""
    holder_name: NotRequired[str]
    holder_type: NotRequired[HolderType]
    r"""The type of holder on a funding source."""
    bank_name: NotRequired[str]
    bank_account_type: NotRequired[BankAccountType]
    r"""The bank account type."""
    routing_number: NotRequired[str]
    last_four_account_number: NotRequired[str]
    updated_on: NotRequired[datetime]
    status_reason: NotRequired[BankAccountStatusReason]
    r"""The reason the bank account status changed to the current value."""
    exception_details: NotRequired[Nullable[ExceptionDetailsTypedDict]]
    r"""Reason for, and details related to, an `errored` or `verificationFailed` bank account status."""
    payment_methods: NotRequired[List[BasicPaymentMethodTypedDict]]
    r"""Includes any payment methods generated for a newly created bank account, removing the need to
    call the List Payment Methods endpoint following a successful Create BankAccount request.

    **NOTE: This field is only populated for Create BankAccount requests made with the `X-Wait-For` header.**

    """


class BankAccountResponse(BaseModel):
    r"""Describes a bank account on a Moov account."""

    bank_account_id: Annotated[Optional[str], pydantic.Field(alias="bankAccountID")] = (
        None
    )
    r"""UUID v4"""

    fingerprint: Optional[str] = None
    r"""Once the bank account is linked, we don't reveal the full bank account number. The fingerprint acts as a way to identify whether two linked bank accounts are the same."""

    status: Optional[BankAccountStatus] = None
    r"""The bank account status."""

    holder_name: Annotated[Optional[str], pydantic.Field(alias="holderName")] = None

    holder_type: Annotated[Optional[HolderType], pydantic.Field(alias="holderType")] = (
        None
    )
    r"""The type of holder on a funding source."""

    bank_name: Annotated[Optional[str], pydantic.Field(alias="bankName")] = None

    bank_account_type: Annotated[
        Optional[BankAccountType], pydantic.Field(alias="bankAccountType")
    ] = None
    r"""The bank account type."""

    routing_number: Annotated[Optional[str], pydantic.Field(alias="routingNumber")] = (
        None
    )

    last_four_account_number: Annotated[
        Optional[str], pydantic.Field(alias="lastFourAccountNumber")
    ] = None

    updated_on: Annotated[Optional[datetime], pydantic.Field(alias="updatedOn")] = None

    status_reason: Annotated[
        Optional[BankAccountStatusReason], pydantic.Field(alias="statusReason")
    ] = None
    r"""The reason the bank account status changed to the current value."""

    exception_details: Annotated[
        OptionalNullable[ExceptionDetails], pydantic.Field(alias="exceptionDetails")
    ] = UNSET
    r"""Reason for, and details related to, an `errored` or `verificationFailed` bank account status."""

    payment_methods: Annotated[
        Optional[List[BasicPaymentMethod]], pydantic.Field(alias="paymentMethods")
    ] = None
    r"""Includes any payment methods generated for a newly created bank account, removing the need to
    call the List Payment Methods endpoint following a successful Create BankAccount request.

    **NOTE: This field is only populated for Create BankAccount requests made with the `X-Wait-For` header.**

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "bankAccountID",
            "fingerprint",
            "status",
            "holderName",
            "holderType",
            "bankName",
            "bankAccountType",
            "routingNumber",
            "lastFourAccountNumber",
            "updatedOn",
            "statusReason",
            "exceptionDetails",
            "paymentMethods",
        ]
        nullable_fields = ["exceptionDetails"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
