"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .cardupdatereason import CardUpdateReason
from datetime import datetime
from moov.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CardAccountUpdaterTypedDict(TypedDict):
    r"""The results of the most recent card update request."""

    updated_on: NotRequired[Nullable[datetime]]
    update_type: NotRequired[CardUpdateReason]
    r"""The results of the card update request."""


class CardAccountUpdater(BaseModel):
    r"""The results of the most recent card update request."""

    updated_on: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="updatedOn")
    ] = UNSET

    update_type: Annotated[
        Optional[CardUpdateReason], pydantic.Field(alias="updateType")
    ] = None
    r"""The results of the card update request."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["updatedOn", "updateType"]
        nullable_fields = ["updatedOn"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
