"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .card import Card, CardTypedDict
from .cardrequest import CardRequest, CardRequestTypedDict
from .schemas_waitfor import SchemasWaitFor
from moov.types import BaseModel
from moov.utils import FieldMetadata, HeaderMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing import Dict, List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class CardRequest1TypedDict(TypedDict):
    account_id: str
    r"""ID of the Moov account representing the cardholder."""
    card_request: CardRequestTypedDict
    x_wait_for: NotRequired[SchemasWaitFor]
    r"""Optional header to wait for certain events, such as the creation of a payment method, to occur before returning a response.

    When this header is set to `payment-method`, the response will include any payment methods that were created for the newly
    linked card in the `paymentMethods` field. Otherwise, the `paymentMethods` field will be omitted from the response.

    """


class CardRequest1(BaseModel):
    account_id: Annotated[
        str,
        pydantic.Field(alias="accountID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""ID of the Moov account representing the cardholder."""

    card_request: Annotated[
        CardRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    x_wait_for: Annotated[
        Optional[SchemasWaitFor],
        pydantic.Field(alias="X-Wait-For"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""Optional header to wait for certain events, such as the creation of a payment method, to occur before returning a response.

    When this header is set to `payment-method`, the response will include any payment methods that were created for the newly
    linked card in the `paymentMethods` field. Otherwise, the `paymentMethods` field will be omitted from the response.

    """


CardResponseResultTypedDict = Union[CardTypedDict, str]


CardResponseResult = Union[Card, str]


class CardResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: CardResponseResultTypedDict


class CardResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: CardResponseResult
