"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .card import Card, CardTypedDict
from enum import Enum
from moov.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class CardPaymentPaymentMethodPaymentMethodType(str, Enum):
    CARD_PAYMENT = "card-payment"


class CardPaymentPaymentMethodTypedDict(TypedDict):
    payment_method_id: str
    r"""ID of the payment method."""
    card: CardTypedDict
    r"""Describes a card on a Moov account."""
    payment_method_type: CardPaymentPaymentMethodPaymentMethodType


class CardPaymentPaymentMethod(BaseModel):
    payment_method_id: Annotated[str, pydantic.Field(alias="paymentMethodID")]
    r"""ID of the payment method."""

    card: Card
    r"""Describes a card on a Moov account."""

    payment_method_type: Annotated[
        CardPaymentPaymentMethodPaymentMethodType,
        pydantic.Field(alias="paymentMethodType"),
    ]
