"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .checkoutcustomeroptions import (
    CheckoutCustomerOptions,
    CheckoutCustomerOptionsTypedDict,
)
from .checkoutdisplayoptions import (
    CheckoutDisplayOptions,
    CheckoutDisplayOptionsTypedDict,
)
from .checkoutpaymentoptions import (
    CheckoutPaymentOptions,
    CheckoutPaymentOptionsTypedDict,
)
from .checkouttransferoptions import (
    CheckoutTransferOptions,
    CheckoutTransferOptionsTypedDict,
)
from datetime import datetime
from enum import Enum
from moov.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CheckoutMode(str, Enum):
    r"""The mode this checkout is allowed to be used within."""

    SANDBOX = "sandbox"
    PRODUCTION = "production"


class CheckoutStatus(str, Enum):
    r"""Status of this checkout."""

    ACTIVE = "active"
    USED = "used"
    DISABLED = "disabled"
    EXPIRED = "expired"


class CheckoutTypedDict(TypedDict):
    r"""Describes a checkout."""

    checkout_code: NotRequired[str]
    r"""Unique code of this checkout.

    """
    created_on: NotRequired[datetime]
    updated_on: NotRequired[datetime]
    last_used_on: NotRequired[Nullable[datetime]]
    disabled_on: NotRequired[Nullable[datetime]]
    partner_account_id: NotRequired[str]
    r"""Moov account ID of the merchant's partner.

    """
    merchant_account_id: NotRequired[str]
    r"""Moov account ID of the merchant.

    """
    mode: NotRequired[CheckoutMode]
    r"""The mode this checkout is allowed to be used within."""
    max_uses: NotRequired[int]
    r"""Maximum number of uses of this checkout.

    """
    uses: NotRequired[int]
    r"""Number of uses of this checkout.

    """
    expires_on: NotRequired[Nullable[datetime]]
    display: NotRequired[CheckoutDisplayOptionsTypedDict]
    customer: NotRequired[CheckoutCustomerOptionsTypedDict]
    payment: NotRequired[CheckoutPaymentOptionsTypedDict]
    transfer: NotRequired[CheckoutTransferOptionsTypedDict]
    link: NotRequired[str]
    r"""URL to the hosted checkout page of this checkout.

    """
    status: NotRequired[CheckoutStatus]
    r"""Status of this checkout.

    """


class Checkout(BaseModel):
    r"""Describes a checkout."""

    checkout_code: Annotated[Optional[str], pydantic.Field(alias="checkoutCode")] = None
    r"""Unique code of this checkout.

    """

    created_on: Annotated[Optional[datetime], pydantic.Field(alias="createdOn")] = None

    updated_on: Annotated[Optional[datetime], pydantic.Field(alias="updatedOn")] = None

    last_used_on: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="lastUsedOn")
    ] = UNSET

    disabled_on: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="disabledOn")
    ] = UNSET

    partner_account_id: Annotated[
        Optional[str], pydantic.Field(alias="partnerAccountID")
    ] = None
    r"""Moov account ID of the merchant's partner.

    """

    merchant_account_id: Annotated[
        Optional[str], pydantic.Field(alias="merchantAccountID")
    ] = None
    r"""Moov account ID of the merchant.

    """

    mode: Optional[CheckoutMode] = None
    r"""The mode this checkout is allowed to be used within."""

    max_uses: Annotated[Optional[int], pydantic.Field(alias="maxUses")] = None
    r"""Maximum number of uses of this checkout.

    """

    uses: Optional[int] = None
    r"""Number of uses of this checkout.

    """

    expires_on: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="expiresOn")
    ] = UNSET

    display: Optional[CheckoutDisplayOptions] = None

    customer: Optional[CheckoutCustomerOptions] = None

    payment: Optional[CheckoutPaymentOptions] = None

    transfer: Optional[CheckoutTransferOptions] = None

    link: Optional[str] = None
    r"""URL to the hosted checkout page of this checkout.

    """

    status: Optional[CheckoutStatus] = None
    r"""Status of this checkout.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "checkoutCode",
            "createdOn",
            "updatedOn",
            "lastUsedOn",
            "disabledOn",
            "partnerAccountID",
            "merchantAccountID",
            "mode",
            "maxUses",
            "uses",
            "expiresOn",
            "display",
            "customer",
            "payment",
            "transfer",
            "link",
            "status",
        ]
        nullable_fields = ["lastUsedOn", "disabledOn", "expiresOn"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
