"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from moov.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateAchDetailsSourceDebitHoldPeriod(str, Enum):
    r"""An optional override of your default ACH hold period in banking days. The hold period must be longer than or equal to your default setting."""

    NO_HOLD = "no-hold"
    ONE_DAY = "1-day"
    TWO_DAYS = "2-days"


class CreateAchDetailsSourceSecCode(str, Enum):
    r"""Code used to identify the ACH authorization method."""

    WEB = "WEB"
    PPD = "PPD"
    CCD = "CCD"
    TEL = "TEL"


class CreateAchDetailsSourceTypedDict(TypedDict):
    r"""If transfer involves ACH, override default card acceptance properties."""

    company_entry_description: NotRequired[str]
    r"""An optional override of the default NACHA company entry description for a transfer."""
    originating_company_name: NotRequired[str]
    r"""An optional override of the default NACHA company name for a transfer."""
    debit_hold_period: NotRequired[Nullable[CreateAchDetailsSourceDebitHoldPeriod]]
    sec_code: NotRequired[Nullable[CreateAchDetailsSourceSecCode]]


class CreateAchDetailsSource(BaseModel):
    r"""If transfer involves ACH, override default card acceptance properties."""

    company_entry_description: Annotated[
        Optional[str], pydantic.Field(alias="companyEntryDescription")
    ] = None
    r"""An optional override of the default NACHA company entry description for a transfer."""

    originating_company_name: Annotated[
        Optional[str], pydantic.Field(alias="originatingCompanyName")
    ] = None
    r"""An optional override of the default NACHA company name for a transfer."""

    debit_hold_period: Annotated[
        OptionalNullable[CreateAchDetailsSourceDebitHoldPeriod],
        pydantic.Field(alias="debitHoldPeriod"),
    ] = UNSET

    sec_code: Annotated[
        OptionalNullable[CreateAchDetailsSourceSecCode], pydantic.Field(alias="secCode")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "companyEntryDescription",
            "originatingCompanyName",
            "debitHoldPeriod",
            "secCode",
        ]
        nullable_fields = ["debitHoldPeriod", "secCode"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
