"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .applicationscope import ApplicationScope
from moov.types import BaseModel
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateApplicationTypedDict(TypedDict):
    r"""Fields required to create an application"""

    name: NotRequired[str]
    r"""Descriptive name allowing spaces."""
    description: NotRequired[str]
    r"""A description for the item."""
    allowed_scopes: NotRequired[List[ApplicationScope]]
    r"""List of allowed scopes that can be requested on another account per their agreement with Moov."""


class CreateApplication(BaseModel):
    r"""Fields required to create an application"""

    name: Optional[str] = None
    r"""Descriptive name allowing spaces."""

    description: Optional[str] = None
    r"""A description for the item."""

    allowed_scopes: Annotated[
        Optional[List[ApplicationScope]], pydantic.Field(alias="allowedScopes")
    ] = None
    r"""List of allowed scopes that can be requested on another account per their agreement with Moov."""
