"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .createdtransferoptions import (
    CreatedTransferOptions,
    CreatedTransferOptionsTypedDict,
)
from moov.types import BaseModel
from typing import Dict, List, Union
from typing_extensions import TypedDict


CreateTransferOptionsResponseResultTypedDict = Union[
    CreatedTransferOptionsTypedDict, str
]


CreateTransferOptionsResponseResult = Union[CreatedTransferOptions, str]


class CreateTransferOptionsResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: CreateTransferOptionsResponseResultTypedDict


class CreateTransferOptionsResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: CreateTransferOptionsResponseResult
