"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .branding import Branding, BrandingTypedDict
from moov.types import BaseModel
from moov.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing import Dict, List, Union
from typing_extensions import Annotated, TypedDict


class CreateBrandingLightTypedDict(TypedDict):
    accent: str
    r"""A CSS hex color representing the accent color for use in light mode."""


class CreateBrandingLight(BaseModel):
    accent: str
    r"""A CSS hex color representing the accent color for use in light mode."""


class CreateBrandingDarkTypedDict(TypedDict):
    accent: str
    r"""A CSS hex color representing the accent color for use in dark mode."""


class CreateBrandingDark(BaseModel):
    accent: str
    r"""A CSS hex color representing the accent color for use in dark mode."""


class CreateBrandingColorsTypedDict(TypedDict):
    light: CreateBrandingLightTypedDict
    dark: CreateBrandingDarkTypedDict


class CreateBrandingColors(BaseModel):
    light: CreateBrandingLight

    dark: CreateBrandingDark


class CreateBrandingCreateBrandingRequestTypedDict(TypedDict):
    colors: CreateBrandingColorsTypedDict


class CreateBrandingCreateBrandingRequest(BaseModel):
    colors: CreateBrandingColors


class CreateBrandingRequestTypedDict(TypedDict):
    account_id: str
    r"""ID of the account."""
    request_body: CreateBrandingCreateBrandingRequestTypedDict


class CreateBrandingRequest(BaseModel):
    account_id: Annotated[
        str,
        pydantic.Field(alias="accountID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""ID of the account."""

    request_body: Annotated[
        CreateBrandingCreateBrandingRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


CreateBrandingResponseResultTypedDict = Union[BrandingTypedDict, str]


CreateBrandingResponseResult = Union[Branding, str]


class CreateBrandingResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: CreateBrandingResponseResultTypedDict


class CreateBrandingResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: CreateBrandingResponseResult
