"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from moov.types import BaseModel
from typing import Dict, List, Union
from typing_extensions import TypedDict


DisableSessionResponseResultTypedDict = Union[str, str]


DisableSessionResponseResult = Union[str, str]


class DisableSessionResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: DisableSessionResponseResultTypedDict


class DisableSessionResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: DisableSessionResponseResult
