"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .enrichmentprofile import EnrichmentProfile, EnrichmentProfileTypedDict
from moov.types import BaseModel
from moov.utils import FieldMetadata, QueryParamMetadata
from typing import Dict, List, Union
from typing_extensions import Annotated, TypedDict


class GetEnrichmentProfileRequestTypedDict(TypedDict):
    email: str
    r"""Valid email address belonging to the profile of interest

    """


class GetEnrichmentProfileRequest(BaseModel):
    email: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""Valid email address belonging to the profile of interest

    """


GetEnrichmentProfileResponseResultTypedDict = Union[EnrichmentProfileTypedDict, str]


GetEnrichmentProfileResponseResult = Union[EnrichmentProfile, str]


class GetEnrichmentProfileResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: GetEnrichmentProfileResponseResultTypedDict


class GetEnrichmentProfileResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: GetEnrichmentProfileResponseResult
