"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .networkids import NetworkIDs, NetworkIDsTypedDict
from moov.types import BaseModel
from moov.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Dict, List, Union
from typing_extensions import Annotated, TypedDict


class GetNetworkIDsRequestTypedDict(TypedDict):
    account_id: str
    r"""ID of the Moov account acting as a merchant in a card transaction."""


class GetNetworkIDsRequest(BaseModel):
    account_id: Annotated[
        str,
        pydantic.Field(alias="accountID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""ID of the Moov account acting as a merchant in a card transaction."""


GetNetworkIDsResponseResultTypedDict = Union[NetworkIDsTypedDict, str]


GetNetworkIDsResponseResult = Union[NetworkIDs, str]


class GetNetworkIDsResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: GetNetworkIDsResponseResultTypedDict


class GetNetworkIDsResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: GetNetworkIDsResponseResult
