"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .paymentmethod import PaymentMethod, PaymentMethodTypedDict
from .paymentmethodtype import PaymentMethodType
from moov.types import BaseModel
from moov.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
import pydantic
from typing import Dict, List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class GetPaymentMethodsRequestTypedDict(TypedDict):
    account_id: str
    r"""ID of the account."""
    source_id: NotRequired[str]
    r"""Optional parameter to filter the account's payment methods by source ID. A source ID can be a [walletID](https://docs.moov.io/api/sources/wallets/list/), [cardID](https://docs.moov.io/api/sources/cards/list/), or [bankAccountID](https://docs.moov.io/api/sources/bank-accounts/list/)."""
    payment_method_type: NotRequired[PaymentMethodType]
    r"""Optional parameter to filter the account's payment methods by payment method type."""


class GetPaymentMethodsRequest(BaseModel):
    account_id: Annotated[
        str,
        pydantic.Field(alias="accountID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""ID of the account."""

    source_id: Annotated[
        Optional[str],
        pydantic.Field(alias="sourceID"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Optional parameter to filter the account's payment methods by source ID. A source ID can be a [walletID](https://docs.moov.io/api/sources/wallets/list/), [cardID](https://docs.moov.io/api/sources/cards/list/), or [bankAccountID](https://docs.moov.io/api/sources/bank-accounts/list/)."""

    payment_method_type: Annotated[
        Optional[PaymentMethodType],
        pydantic.Field(alias="paymentMethodType"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Optional parameter to filter the account's payment methods by payment method type."""


GetPaymentMethodsResponseResultTypedDict = Union[List[PaymentMethodTypedDict], str]


GetPaymentMethodsResponseResult = Union[List[PaymentMethod], str]


class GetPaymentMethodsResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: GetPaymentMethodsResponseResultTypedDict


class GetPaymentMethodsResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: GetPaymentMethodsResponseResult
