"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .wallettransaction import WalletTransaction, WalletTransactionTypedDict
from moov.types import BaseModel
from moov.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Dict, List, Union
from typing_extensions import Annotated, TypedDict


class GetWalletTransactionRequestTypedDict(TypedDict):
    account_id: str
    r"""ID of the account."""
    wallet_id: str
    r"""ID of the wallet"""
    transaction_id: str
    r"""ID associated with the wallet transaction."""


class GetWalletTransactionRequest(BaseModel):
    account_id: Annotated[
        str,
        pydantic.Field(alias="accountID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""ID of the account."""

    wallet_id: Annotated[
        str,
        pydantic.Field(alias="walletID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""ID of the wallet"""

    transaction_id: Annotated[
        str,
        pydantic.Field(alias="transactionID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""ID associated with the wallet transaction."""


GetWalletTransactionResponseResultTypedDict = Union[WalletTransactionTypedDict, str]


GetWalletTransactionResponseResult = Union[WalletTransaction, str]


class GetWalletTransactionResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: GetWalletTransactionResponseResultTypedDict


class GetWalletTransactionResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: GetWalletTransactionResponseResult
