"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from moov.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PatchRepresentativeRequestNameTypedDict(TypedDict):
    r"""An individual's name."""

    first_name: NotRequired[Nullable[str]]
    middle_name: NotRequired[Nullable[str]]
    last_name: NotRequired[Nullable[str]]
    suffix: NotRequired[Nullable[str]]


class PatchRepresentativeRequestName(BaseModel):
    r"""An individual's name."""

    first_name: Annotated[OptionalNullable[str], pydantic.Field(alias="firstName")] = (
        UNSET
    )

    middle_name: Annotated[
        OptionalNullable[str], pydantic.Field(alias="middleName")
    ] = UNSET

    last_name: Annotated[OptionalNullable[str], pydantic.Field(alias="lastName")] = (
        UNSET
    )

    suffix: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["firstName", "middleName", "lastName", "suffix"]
        nullable_fields = ["firstName", "middleName", "lastName", "suffix"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


class PatchRepresentativeRequestPhoneTypedDict(TypedDict):
    number: NotRequired[Nullable[str]]
    country_code: NotRequired[Nullable[str]]


class PatchRepresentativeRequestPhone(BaseModel):
    number: OptionalNullable[str] = UNSET

    country_code: Annotated[
        OptionalNullable[str], pydantic.Field(alias="countryCode")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["number", "countryCode"]
        nullable_fields = ["number", "countryCode"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


class PatchRepresentativeRequestAddressTypedDict(TypedDict):
    r"""An individual's residential address. Business addresses not accepted."""

    address_line1: NotRequired[Nullable[str]]
    address_line2: NotRequired[Nullable[str]]
    city: NotRequired[Nullable[str]]
    state_or_province: NotRequired[Nullable[str]]
    postal_code: NotRequired[Nullable[str]]
    country: NotRequired[Nullable[str]]


class PatchRepresentativeRequestAddress(BaseModel):
    r"""An individual's residential address. Business addresses not accepted."""

    address_line1: Annotated[
        OptionalNullable[str], pydantic.Field(alias="addressLine1")
    ] = UNSET

    address_line2: Annotated[
        OptionalNullable[str], pydantic.Field(alias="addressLine2")
    ] = UNSET

    city: OptionalNullable[str] = UNSET

    state_or_province: Annotated[
        OptionalNullable[str], pydantic.Field(alias="stateOrProvince")
    ] = UNSET

    postal_code: Annotated[
        OptionalNullable[str], pydantic.Field(alias="postalCode")
    ] = UNSET

    country: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "addressLine1",
            "addressLine2",
            "city",
            "stateOrProvince",
            "postalCode",
            "country",
        ]
        nullable_fields = [
            "addressLine1",
            "addressLine2",
            "city",
            "stateOrProvince",
            "postalCode",
            "country",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


class PatchRepresentativeRequestBirthDateTypedDict(TypedDict):
    r"""An individual's birthdate."""

    day: int
    month: int
    year: int


class PatchRepresentativeRequestBirthDate(BaseModel):
    r"""An individual's birthdate."""

    day: int

    month: int

    year: int


class PatchRepresentativeRequestSsnTypedDict(TypedDict):
    full: NotRequired[str]
    last_four: NotRequired[str]


class PatchRepresentativeRequestSsn(BaseModel):
    full: Optional[str] = None

    last_four: Annotated[Optional[str], pydantic.Field(alias="lastFour")] = None


class PatchRepresentativeRequestItinTypedDict(TypedDict):
    full: NotRequired[str]
    last_four: NotRequired[str]


class PatchRepresentativeRequestItin(BaseModel):
    full: Optional[str] = None

    last_four: Annotated[Optional[str], pydantic.Field(alias="lastFour")] = None


class PatchRepresentativeRequestGovernmentIDTypedDict(TypedDict):
    ssn: NotRequired[Nullable[PatchRepresentativeRequestSsnTypedDict]]
    itin: NotRequired[Nullable[PatchRepresentativeRequestItinTypedDict]]


class PatchRepresentativeRequestGovernmentID(BaseModel):
    ssn: OptionalNullable[PatchRepresentativeRequestSsn] = UNSET

    itin: OptionalNullable[PatchRepresentativeRequestItin] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["ssn", "itin"]
        nullable_fields = ["ssn", "itin"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


class PatchRepresentativeRequestResponsibilitiesTypedDict(TypedDict):
    r"""Describes the job responsibilities of an individual."""

    is_controller: NotRequired[Nullable[bool]]
    r"""Indicates whether this individual has significant management responsibilities within the business."""
    is_owner: NotRequired[Nullable[bool]]
    r"""If `true`, this field indicates the individual has a business ownership stake of at least 25% in the business. If the representative does not own at least 25% of the business, this field should be `false`."""
    ownership_percentage: NotRequired[Nullable[int]]
    r"""The percentage of ownership this individual has in the business (required if `isOwner` is `true`)."""
    job_title: NotRequired[Nullable[str]]


class PatchRepresentativeRequestResponsibilities(BaseModel):
    r"""Describes the job responsibilities of an individual."""

    is_controller: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="isController")
    ] = False
    r"""Indicates whether this individual has significant management responsibilities within the business."""

    is_owner: Annotated[OptionalNullable[bool], pydantic.Field(alias="isOwner")] = False
    r"""If `true`, this field indicates the individual has a business ownership stake of at least 25% in the business. If the representative does not own at least 25% of the business, this field should be `false`."""

    ownership_percentage: Annotated[
        OptionalNullable[int], pydantic.Field(alias="ownershipPercentage")
    ] = UNSET
    r"""The percentage of ownership this individual has in the business (required if `isOwner` is `true`)."""

    job_title: Annotated[OptionalNullable[str], pydantic.Field(alias="jobTitle")] = (
        UNSET
    )

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["isController", "isOwner", "ownershipPercentage", "jobTitle"]
        nullable_fields = ["isController", "isOwner", "ownershipPercentage", "jobTitle"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


class PatchRepresentativeRequestTypedDict(TypedDict):
    r"""Describes the fields available when patching a representative."""

    name: NotRequired[Nullable[PatchRepresentativeRequestNameTypedDict]]
    phone: NotRequired[Nullable[PatchRepresentativeRequestPhoneTypedDict]]
    email: NotRequired[Nullable[str]]
    address: NotRequired[Nullable[PatchRepresentativeRequestAddressTypedDict]]
    birth_date: NotRequired[Nullable[PatchRepresentativeRequestBirthDateTypedDict]]
    government_id: NotRequired[
        Nullable[PatchRepresentativeRequestGovernmentIDTypedDict]
    ]
    responsibilities: NotRequired[
        Nullable[PatchRepresentativeRequestResponsibilitiesTypedDict]
    ]


class PatchRepresentativeRequest(BaseModel):
    r"""Describes the fields available when patching a representative."""

    name: OptionalNullable[PatchRepresentativeRequestName] = UNSET

    phone: OptionalNullable[PatchRepresentativeRequestPhone] = UNSET

    email: OptionalNullable[str] = UNSET

    address: OptionalNullable[PatchRepresentativeRequestAddress] = UNSET

    birth_date: Annotated[
        OptionalNullable[PatchRepresentativeRequestBirthDate],
        pydantic.Field(alias="birthDate"),
    ] = UNSET

    government_id: Annotated[
        OptionalNullable[PatchRepresentativeRequestGovernmentID],
        pydantic.Field(alias="governmentID"),
    ] = UNSET

    responsibilities: OptionalNullable[PatchRepresentativeRequestResponsibilities] = (
        UNSET
    )

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "name",
            "phone",
            "email",
            "address",
            "birthDate",
            "governmentID",
            "responsibilities",
        ]
        nullable_fields = [
            "name",
            "phone",
            "email",
            "address",
            "birthDate",
            "governmentID",
            "responsibilities",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
