"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .patchtransfer import PatchTransfer, PatchTransferTypedDict
from .transfer1 import Transfer2, Transfer2TypedDict
from moov.types import BaseModel
from moov.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing import Dict, List, Union
from typing_extensions import Annotated, TypedDict


class PatchTransferRequestTypedDict(TypedDict):
    transfer_id: str
    r"""Identifier for the transfer."""
    patch_transfer: PatchTransferTypedDict


class PatchTransferRequest(BaseModel):
    transfer_id: Annotated[
        str,
        pydantic.Field(alias="transferID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Identifier for the transfer."""

    patch_transfer: Annotated[
        PatchTransfer,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


PatchTransferResponseResultTypedDict = Union[Transfer2TypedDict, str]


PatchTransferResponseResult = Union[Transfer2, str]


class PatchTransferResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: PatchTransferResponseResultTypedDict


class PatchTransferResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: PatchTransferResponseResult
