"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from moov.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class PlaidIntegrationTypedDict(TypedDict):
    r"""The details of a Plaid processor integration for a linked funding source. <br><br> `sandbox` - When linking a bank account to a `sandbox` account using a Plaid processor token a default bank account response will be used. The following default data will be used to generate the bank account in this flow:
    ```
    RoutingNumber: \"011401533\",
    AccountNumber: \"1111222233330000\",
    AccountType:   \"checking\",
    Mask:          \"0000\"
    ```

    """

    token: NotRequired[str]


class PlaidIntegration(BaseModel):
    r"""The details of a Plaid processor integration for a linked funding source. <br><br> `sandbox` - When linking a bank account to a `sandbox` account using a Plaid processor token a default bank account response will be used. The following default data will be used to generate the bank account in this flow:
    ```
    RoutingNumber: \"011401533\",
    AccountNumber: \"1111222233330000\",
    AccountType:   \"checking\",
    Mask:          \"0000\"
    ```

    """

    token: Optional[str] = None
