"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .rtpfailurecode import RTPFailureCode
from .rtpstatus import RTPStatus
from datetime import datetime
from moov.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, NotRequired, TypedDict


class RTPDetailsTypedDict(TypedDict):
    r"""RTP specific details about the transaction."""

    status: RTPStatus
    r"""Status of the RTP lifecycle."""
    network_response_code: NotRequired[Nullable[str]]
    r"""Code returned by rail network on failure."""
    failure_code: NotRequired[Nullable[RTPFailureCode]]
    r"""Status codes for RTP failures."""
    initiated_on: NotRequired[Nullable[datetime]]
    completed_on: NotRequired[Nullable[datetime]]
    failed_on: NotRequired[Nullable[datetime]]
    accepted_without_posting_on: NotRequired[Nullable[datetime]]


class RTPDetails(BaseModel):
    r"""RTP specific details about the transaction."""

    status: RTPStatus
    r"""Status of the RTP lifecycle."""

    network_response_code: Annotated[
        OptionalNullable[str], pydantic.Field(alias="networkResponseCode")
    ] = UNSET
    r"""Code returned by rail network on failure."""

    failure_code: Annotated[
        OptionalNullable[RTPFailureCode], pydantic.Field(alias="failureCode")
    ] = UNSET
    r"""Status codes for RTP failures."""

    initiated_on: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="initiatedOn")
    ] = UNSET

    completed_on: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="completedOn")
    ] = UNSET

    failed_on: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="failedOn")
    ] = UNSET

    accepted_without_posting_on: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="acceptedWithoutPostingOn")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "networkResponseCode",
            "failureCode",
            "initiatedOn",
            "completedOn",
            "failedOn",
            "acceptedWithoutPostingOn",
        ]
        nullable_fields = [
            "networkResponseCode",
            "failureCode",
            "initiatedOn",
            "completedOn",
            "failedOn",
            "acceptedWithoutPostingOn",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
