"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from moov.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class SetupTypedDict(TypedDict):
    r"""Properties for password authentication"""

    token: str
    r"""Base64 string of data."""
    password: str
    r"""Describes a password for a user"""
    given_name: str
    r"""Name this person was given. This is usually the same as first name."""
    family_name: str
    r"""Family name of this person. This is usually the same as last name."""
    fingerprint: str
    r"""Device hash generated by a frontend library."""


class Setup(BaseModel):
    r"""Properties for password authentication"""

    token: str
    r"""Base64 string of data."""

    password: str
    r"""Describes a password for a user"""

    given_name: Annotated[str, pydantic.Field(alias="givenName")]
    r"""Name this person was given. This is usually the same as first name."""

    family_name: Annotated[str, pydantic.Field(alias="familyName")]
    r"""Family name of this person. This is usually the same as last name."""

    fingerprint: str
    r"""Device hash generated by a frontend library."""
