"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dispute import Dispute, DisputeTypedDict
from moov.types import BaseModel
from moov.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Dict, List, Union
from typing_extensions import Annotated, TypedDict


class SubmitEvidenceRequestTypedDict(TypedDict):
    dispute_id: str
    r"""ID of dispute"""


class SubmitEvidenceRequest(BaseModel):
    dispute_id: Annotated[
        str,
        pydantic.Field(alias="disputeID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""ID of dispute"""


SubmitEvidenceResponseResultTypedDict = Union[DisputeTypedDict, str]


SubmitEvidenceResponseResult = Union[Dispute, str]


class SubmitEvidenceResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: SubmitEvidenceResponseResultTypedDict


class SubmitEvidenceResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: SubmitEvidenceResponseResult
