"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .availablebalance import AvailableBalance, AvailableBalanceTypedDict
from moov.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class WalletTypedDict(TypedDict):
    r"""A Moov wallet to store funds for transfers."""

    wallet_id: str
    r"""UUID v4"""
    available_balance: AvailableBalanceTypedDict
    r"""Available balance of the wallet."""


class Wallet(BaseModel):
    r"""A Moov wallet to store funds for transfers."""

    wallet_id: Annotated[str, pydantic.Field(alias="walletID")]
    r"""UUID v4"""

    available_balance: Annotated[
        AvailableBalance, pydantic.Field(alias="availableBalance")
    ]
    r"""Available balance of the wallet."""
