"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .status import Status
from datetime import datetime
from moov.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class WebhookTypedDict(TypedDict):
    webhook_id: str
    r"""Unique identifier for this webhook."""
    url: str
    r"""The URL of the webhook endpoint. Event payloads will be delivered to this URL."""
    status: Status
    r"""The status of the resource."""
    event_types: List[str]
    r"""The list of event types that the webhook is subscribed to.
    `[\"*\"]` indicates the webhook is subscribed to all current and future event types.

    """
    created_on: datetime
    updated_on: datetime
    description: NotRequired[str]
    r"""An optional description of what the webhook is used for."""
    last_used_on: NotRequired[Nullable[datetime]]


class Webhook(BaseModel):
    webhook_id: Annotated[str, pydantic.Field(alias="webhookID")]
    r"""Unique identifier for this webhook."""

    url: str
    r"""The URL of the webhook endpoint. Event payloads will be delivered to this URL."""

    status: Status
    r"""The status of the resource."""

    event_types: Annotated[List[str], pydantic.Field(alias="eventTypes")]
    r"""The list of event types that the webhook is subscribed to.
    `[\"*\"]` indicates the webhook is subscribed to all current and future event types.

    """

    created_on: Annotated[datetime, pydantic.Field(alias="createdOn")]

    updated_on: Annotated[datetime, pydantic.Field(alias="updatedOn")]

    description: Optional[str] = None
    r"""An optional description of what the webhook is used for."""

    last_used_on: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="lastUsedOn")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["description", "lastUsedOn"]
        nullable_fields = ["lastUsedOn"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
