"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from moov.types import BaseModel
from typing_extensions import TypedDict


class WebhookSecretKeyTypedDict(TypedDict):
    r"""Webhook secret key used to verify that a request came from Moov"""

    secret: str


class WebhookSecretKey(BaseModel):
    r"""Webhook secret key used to verify that a request came from Moov"""

    secret: str
